openapi: 3.0.0
info:
  title: Admin Panel API
  description: API documentation for Admin Panel API
  version: 0.1.9

components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT

servers:
  - url: http://localhost:3000
    description: local server
  - url: http://producation.app
    description: production server

paths:
  /auth:
    post:
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
            example:
              email: sabavar@redberry.ge
              password: password123
      responses:
        '201':
          description: JWT token generated successfully.

  /add-company:
    post:
      security:
        - bearerAuth: []
      tags:
        - Company
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                website:
                  type: string
                logoUrl:
                  type: string
                establishmentDate:
                  type: string
            example:
              name: Redberry
              website: https://redberry.international/
              logoUrl: https://redberry.international/wp-content/uploads/2022/01/redberrylogo.svg
              establishmentDate: Jun 10 2014
      responses:
        '201':
          description: Company saved successfully.
        '404':
          description: Company save failed.

  /add-employee:
    post:
      security:
        - bearerAuth: []
      tags:
        - Employee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                startedAt:
                  type: string
                birthDate:
                  type: string
                personalNumber:
                  type: string
                position:
                  type: string
                id:
                  type: string
            example:
              firstName: Saba
              lastName: Vartasashvili
              startedAt: Mar 10 2022
              birthDate: Jan 8 2002
              personalNumber: '12345678910'
              position: Xaker
              id: 62a37de8c9bc3021399cad31
      responses:
        '201':
          description: Employee saved successfully.
        '404':
          description: Company not found.
